# Generated by Django 4.2.4 on 2023-08-16 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfappraisalform',
            name='beyond_syllabus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='learning_methodology',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='modifications_in_teaching',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='projects_guided',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='students_guided',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='additional_qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='areas_of_specialization',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='first_designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='present_designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='present_pay_scale_and_pay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='pursuing_higher_studies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='qualifications',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='KnowledgeResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('resources_consulted', models.TextField()),
                ('resources_prescribed', models.TextField()),
                ('additional_resources_provided', models.TextField()),
                ('self_assessed_api_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfappraisal.selfappraisalform')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationDuties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_papers_set', models.JSONField(default={'PG': [0, 0, 0], 'UG': [0, 0, 0]})),
                ('ab_evaluated', models.JSONField(default={'PG': [0, 0, 0], 'UG': [0, 0, 0]})),
                ('students_examined', models.JSONField(default={'PG': [0, 0, 0], 'UG': [0, 0, 0]})),
                ('invigilation_duties', models.JSONField(default={'ALLOTED': [0, 0, 0], 'Performed': [0, 0, 0]})),
                ('api_score', models.IntegerField()),
                ('hod_remarks', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfappraisal.selfappraisalform')),
            ],
        ),
    ]
