# Generated by Django 4.2.4 on 2023-08-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfappraisalform',
            name='written_works',
        ),
    ]
