# Generated by Django 4.2.4 on 2023-08-16 05:12

from django.db import migrations, models
import selfappraisal.models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0002_selfappraisalform_beyond_syllabus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationduties',
            name='ab_evaluated',
            field=models.JSONField(default=selfappraisal.models.EvaluationDuties.default_json),
        ),
        migrations.AlterField(
            model_name='evaluationduties',
            name='invigilation_duties',
            field=models.JSONField(default=selfappraisal.models.EvaluationDuties.default_json_duties),
        ),
        migrations.AlterField(
            model_name='evaluationduties',
            name='q_papers_set',
            field=models.JSONField(default=selfappraisal.models.EvaluationDuties.default_json),
        ),
        migrations.AlterField(
            model_name='evaluationduties',
            name='students_examined',
            field=models.JSONField(default=selfappraisal.models.EvaluationDuties.default_json),
        ),
    ]
