# Generated by Django 4.2.4 on 2023-08-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0002_remove_selfappraisalform_written_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfappraisalform',
            name='additional_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='areas_of_specialization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='beyond_syllabus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='first_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='learning_methodology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='modifications_in_teaching',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='present_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='present_pay_scale_and_pay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='projects_guided',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='pursuing_higher_studies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='qualifications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='students_guided',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
