# Generated by Django 4.2.4 on 2023-08-16 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0003_alter_evaluationduties_ab_evaluated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfappraisalform',
            name='departmental_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='institute_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='invited_lectures',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='students_extra_curricular',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='written_works',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_names', models.TextField(verbose_name='Names of All Authors in Order as in Publication')),
                ('title_reference', models.TextField(verbose_name='Title and Complete Reference in IEEE Style')),
                ('publication_type', models.CharField(max_length=100, verbose_name='Type of Publication/Conference etc.')),
                ('api_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Self Assessed API Score')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks by the HoD')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfappraisal.selfappraisalform')),
            ],
        ),
    ]
