# Generated by Django 4.2.4 on 2023-08-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0003_alter_selfappraisalform_additional_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfappraisalform',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
