# Generated by Django 4.2.4 on 2023-08-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0004_alter_selfappraisalform_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='remarks',
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='courses_remarks_even',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks by the HoD'),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='courses_remarks_odd',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks by the HoD'),
        ),
    ]
