# Generated by Django 4.2.4 on 2023-08-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0004_alter_selfappraisalform_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attended_organized',
            field=models.CharField(blank=True, choices=[('Attended', 'Attended'), ('Organized', 'Organized')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_held',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsoring_agency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='additional_qualifications',
            field=models.TextField(blank=True, null=True, verbose_name='9. Additional Qualification acquired during the year (Give full details)'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='areas_of_specialization',
            field=models.TextField(blank=True, null=True, verbose_name='8. Areas of Specialization and Current Interest'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='5. University Joining Date'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='department',
            field=models.CharField(max_length=100, verbose_name='2. Department'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='first_designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='6. First Designation'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='present_designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='4. Present Designation'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='present_pay_scale_and_pay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='7. Present Pay Scale & Pay'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='pursuing_higher_studies',
            field=models.TextField(blank=True, null=True, verbose_name='10. Pursuing Higher Studies (Give full details)'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='qualifications',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3. Qualifications'),
        ),
    ]
