# Generated by Django 4.2.4 on 2023-08-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0005_alter_event_attended_organized_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ODD SEM'), (2, 'EVEN SEM')], default=1),
        ),
    ]
