# Generated by Django 4.2.4 on 2023-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0006_selfappraisalform_knowledge_resources_reamrks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfappraisalform',
            name='knowledge_resources_reamrks',
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='knowledge_resources_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Knowledge Resources Remarks (give details)'),
        ),
    ]
