# Generated by Django 4.2.4 on 2023-08-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0006_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeresources',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgeresources',
            name='self_assessed_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
