# Generated by Django 4.2.4 on 2023-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0007_remove_selfappraisalform_knowledge_resources_reamrks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfappraisalform',
            name='projects_guided_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks by the HoD'),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='students_guided_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks by the HoD'),
        ),
    ]
