# Generated by Django 4.2.4 on 2023-08-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0007_alter_knowledgeresources_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfappraisalform',
            name='articles_monographs',
            field=models.TextField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='beyond_syllabus',
            field=models.TextField(blank=True, null=True, verbose_name='Any Coverage/ Introduction beyond syllabus ( give brief details )'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='departmental_activities',
            field=models.TextField(blank=True, verbose_name='(B) Contribution/ Participation in Departmental Activities & Development:'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='institute_activities',
            field=models.TextField(blank=True, verbose_name='(C) Contribution/ Participation in Institute Activities & Development:'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='invited_lectures',
            field=models.TextField(blank=True, verbose_name='(D) Special/ Extension/ Expert/Invited Lectures Delivered, Give Details:'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='learning_methodology',
            field=models.TextField(blank=True, null=True, verbose_name='Participatory/Innovative Teaching Learning Methodologies used (give brief details)'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='modifications_in_teaching',
            field=models.TextField(blank=True, null=True, verbose_name='Any Modification/ Addition to syllabus (give brief details)'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='students_extra_curricular',
            field=models.TextField(blank=True, verbose_name='(A) Contribution/ Participation in Students Extra & Co- Curricular activities:'),
        ),
    ]
