# Generated by Django 4.2.4 on 2023-08-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0008_selfappraisalform_projects_guided_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfappraisalform',
            name='projects_guided_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Number of Projects Guided Remarks by the HoD'),
        ),
        migrations.AlterField(
            model_name='selfappraisalform',
            name='students_guided_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Number of Students Guided Remarks by the HoD'),
        ),
    ]
