# Generated by Django 4.2.4 on 2023-08-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0008_selfappraisalform_articles_monographs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfappraisalform',
            name='articles_monographs',
            field=models.TextField(blank=True, verbose_name='(E) Articles, Monographs, Technical Reports, Reviews Written, Give Details:'),
        ),
    ]
