# Generated by Django 4.2.4 on 2023-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0009_alter_selfappraisalform_projects_guided_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfappraisalform',
            name='examination_duties_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks by the HoD'),
        ),
    ]
