# Generated by Django 4.2.4 on 2023-08-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0009_alter_selfappraisalform_articles_monographs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='amount_sanctioned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Sanctioned'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='chief_investigator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chief or Co Investigator Specify'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='sanction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sanction Date'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='sponsoring_agency',
            field=models.TextField(blank=True, null=True, verbose_name='Details of Sponsoring Agency'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title of Research Project/Consultancy Work'),
        ),
    ]
