# Generated by Django 4.2.4 on 2023-08-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0010_alter_researchproject_amount_sanctioned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_choice',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Research Papers Published/ Presented'), (2, 'Books, Chapters in Books Written')], default=1),
        ),
    ]
