# Generated by Django 4.2.4 on 2023-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0010_selfappraisalform_examination_duties_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfappraisalform',
            name='books_remarks',
            field=models.TextField(blank=True, verbose_name='Remarks by HOD'),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='overall_remarks',
            field=models.TextField(blank=True, verbose_name='Overall Remarks by HOD'),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='research_guidance_remarks',
            field=models.TextField(blank=True, verbose_name='Remarks by HOD'),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='research_paper_remarks',
            field=models.TextField(blank=True, verbose_name='Remarks by HOD'),
        ),
        migrations.AddField(
            model_name='selfappraisalform',
            name='research_projects_remarks',
            field=models.TextField(blank=True, verbose_name='Remarks by HOD'),
        ),
    ]
