# Generated by Django 4.2.4 on 2023-08-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0011_publication_publication_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_choice',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Research Papers Published/ Presented'), (2, 'Books, Chapters in Books Written')]),
        ),
    ]
