# Generated by Django 4.2.4 on 2023-08-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0012_alter_publication_publication_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationduties',
            name='api_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationduties',
            name='hod_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
