# Generated by Django 4.2.4 on 2023-08-23 08:08

from django.db import migrations, models
import selfappraisal.models


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0013_alter_evaluationduties_api_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationduties',
            name='ab_evaluated',
            field=models.JSONField(blank=True, default=selfappraisal.models.EvaluationDuties.default_json, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationduties',
            name='invigilation_duties',
            field=models.JSONField(blank=True, default=selfappraisal.models.EvaluationDuties.default_json_duties, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationduties',
            name='q_papers_set',
            field=models.JSONField(blank=True, default=selfappraisal.models.EvaluationDuties.default_json, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationduties',
            name='students_examined',
            field=models.JSONField(blank=True, default=selfappraisal.models.EvaluationDuties.default_json, null=True),
        ),
    ]
