# Generated by Django 4.2.4 on 2023-08-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfappraisal', '0014_alter_evaluationduties_ab_evaluated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationduties',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='selfappraisal.selfappraisalform'),
        ),
    ]
